### ISSUE TITLE
Приложение крашится при использовании штатного AdMob

### ISSUE THREAD

**Issue by KonstantinTsu** [kulichin/UnrealFirebaseAnalytics#1]
Добавил все по инструкции - отдельно без штатного admob вроде работает, если добавлять плигин - краш на устростве при запуске. Один раз что-то там не находил (были подробности в ошибке на устройстве)
будут вопросы, пишите на glazcentr61@gmail.com
мой.build.cs
// Fill out your copyright notice in the Description page of Project Settings.

using UnrealBuildTool;

public class Cards_mig3007_eng : ModuleRules
{
	public Cards_mig3007_eng(ReadOnlyTargetRules Target) : base(Target)
	{
		PCHUsage = PCHUsageMode.UseExplicitOrSharedPCHs;
	
		PublicDependencyModuleNames.AddRange(new string[] { "Core", "FirebaseAnalytics", "CoreUObject", "Engine", "InputCore" });

		PrivateDependencyModuleNames.AddRange(new string[] {  });

		// Uncomment if you are using Slate UI
		// PrivateDependencyModuleNames.AddRange(new string[] { "Slate", "SlateCore" });
		
		// Uncomment if you are using online features
		// PrivateDependencyModuleNames.Add("OnlineSubsystem");
		PrivateDependencyModuleNames.Add("OnlineSubsystem");
		PrivateDependencyModuleNames.Add("AndroidAdvertising");

		// To include OnlineSubsystemSteam, add it to the plugins section in your uproject file with the Enabled attribute set to true
	}
}

**Comment by kulichin** [comment]
Сделал фикс, теперь все должно работать нормально :)
