### ISSUE TITLE
Не отправляет event в firebase

### ISSUE THREAD

**Issue by ViktorZam** [kulichin/UnrealFirebaseAnalytics#3]
ставлю на кнопку Log Event, но в косоле Firebase, этого ивента не нахожу
![изображение](https://user-images.githubusercontent.com/42400969/139249122-48c1d001-5f53-444d-b816-46b7ea936afd.png)
хотя debug view проходит нормально

**Comment by kulichin** [comment]
Это нормальное явление. Обычно они появляются там через пару часов

**Comment by ViktorZam** [comment]
так у меня так со вчерашнего дня... я думал там телефон статистику вообще отправляет через день, но я до сих пор не вижу, кроме стандартных ивентов

**Comment by kulichin** [comment]
А вы точно отправляли эти ивенты без каких либо дебаг параметров? Просто ивенты, которые были отправлены с дебаг параметрами в конечном итоге не будут отображаться в панели.

**Comment by ViktorZam** [comment]
я делал вот так 
![изображение](https://user-images.githubusercontent.com/42400969/139252693-7ea52fbe-c40e-4b7f-ab1d-65d8d8280f42.png)

тут не трогал ничего 
![изображение](https://user-images.githubusercontent.com/42400969/139252781-fdeb432a-298a-4b41-b06c-e01641499e6b.png)

и вот в консоле так(вместо package - название проекта в настройках проекта(android))
![изображение](https://user-images.githubusercontent.com/42400969/139252932-f516d742-62d2-4577-bf39-7de1eb23b16f.png)

также выключал в консоле и просто отправлял log event

единственное что ивент появился тут
![изображение](https://user-images.githubusercontent.com/42400969/139253192-9d52fd63-464d-452c-a0fd-4ca2b943abe4.png)

но это вчерашний, а в ивентах он не появился...

пробовал разные ноды с параметрами и без, и как в примере и с дебагом и без него, не сработало..

**Comment by ViktorZam** [comment]
Всё, появились
![изображение](https://user-images.githubusercontent.com/42400969/139394488-3dc95ea4-8373-40b6-80fd-db1518eaf5f8.png)

Походу кастомные события появляются в консоле через день
